apiVersion: v1                                                                  
kind: Pod
metadata:
   name: test
spec:
  containers:
     - name: c2
       image: quay.io/pranavadmin/nginxdemo
       imagePullPolicy: IfNotPresent
